service: shift-code-feed-reader

provider:
  name: google
  stage: dev
  runtime: python37
  region: us-central1
  project: ${env:PROJECT_ID}
  # The GCF credentials can be a little tricky to set up. Luckily we've documented this for you here:
  # https://serverless.com/framework/docs/providers/google/guide/credentials/
  #
  # the path to the credentials file needs to be absolute
  credentials: ~/.gcloud/shift-code-reader-serverless-keyfile.json

plugins:
  - serverless-google-cloudfunctions
package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**
  include:
    - src/**
    - creds/**

functions:
  getCodes:
    handler: get_codes
    events:
      - http: path
    environment:
      SLACK_TOKEN: ${env:SLACK_TOKEN}
      GCLOUD_BUCKET_NAME: ${env:GCLOUD_BUCKET_NAME}
